<?php
/* $Id$ */

/**
 * Implementation of hook_install().
 */
function user_delete_install() {
  switch ($GLOBALS['db_type']) {
    case 'mysql':
    case 'mysqli':
      db_query("UPDATE {system} SET weight=-1 WHERE name='user_delete'");
      break;
    case 'pgsql':
      db_query("UPDATE {system} SET weight=-1 WHERE name='user_delete'");
      break;
  }
}

/**
 * Implementation of hook_uninstall();
 */
function user_delete_uninstall() {
  db_query('DROP TABLE {user_delete}');
}