<?php
/* $Id$ */

/**
 * User delete
 * 
 * @file
 * Let users delete their own account.
 *
 * This module will be abandoned when http://drupal.org/node/8 is fixed.
 * 
 * Note: As of January 8, 2009 - 09:44 the issue is marked as fixed.
 * And commited to Drupal 7, see http://drupal.org/node/8#comment-1188824
 *
 * @author
 * Stefan Auditor <stefan.auditor@erdfisch.de>
 */

/**
 * Implementation of hook_perm().
 */
function user_delete_perm() {
  return array('delete own account');
}

/**
 * Implementation of hook_menu().
 */
function user_delete_menu() {
  $items['admin/user/user_delete'] = array(
    'title' => 'User delete',
    'description' => "Configure the user delete action.",
    'page callback' => 'drupal_get_form',
    'page arguments' => array('user_delete_settings'),
    'access arguments' => array('administer users'),
    'file' => 'user_delete.admin.inc',
  );
  return $items;
}

/**
 * Implementation of hook_menu_alter().
 */
function user_delete_menu_alter(&$callbacks) {
  $callbacks['user/%user/delete']['access callback'] = 'user_delete_access';
  $callbacks['user/%user/delete']['access arguments'] = array(1);
  $callbacks['user/%user/delete']['type'] = MENU_LOCAL_TASK;
}

/**
 * Checks whether a user can delete an account
 */
function user_delete_access($account) {
  global $user;
  return (user_access('administer users') || (user_access('delete own account') && $account->uid == $user->uid));
}

/**
 * Implementation of hook_form_user_profile_form_alter().
*/
function user_delete_form_user_profile_form_alter($form, &$form_state) {
  global $user;
  if (user_access('delete own account') && arg(1) == $user->uid) {
    $form['delete'] = array(
      '#type' => 'submit',
      '#value' => t('Delete'),
      '#weight' => 31,
      '#submit' => array('user_edit_delete_submit'),
    );
  }
}

/**
 * Implementation of hook_user().
 */
function user_delete_user($op, &$edit, &$account, $category = NULL) {
  global $user;

  //Note: $account->uid and $user->uid are still available!
  if ($op == 'delete' && ($account->uid == $user->uid)) {
    //TODO: add additional actions based on http://drupal.org/node/8#comment-628434
    
    //Imitate default behaviour
    //Assign all nodes and comments to anonymous
    db_query("UPDATE {node} SET uid=0 WHERE uid=%d", $account->uid);
    db_query("UPDATE {comments} SET uid=0 WHERE uid=%d", $account->uid);
    
    //Redirect
    drupal_goto(variable_get('user_delete_redirect', '<front>'));
  }
}
